#!/usr/local/bin/escript

main([Port]) ->
	simple_tcp_server:create(Port, {yar_server, test_drive}),
	main_loop();
main([]) ->
	io:format("Usage: xxx PORT~n").

main_loop() ->
	receive
		_ ->
			main_loop()
	end.

